.MODEL SMALL  
.STACK 64H  
.DATA  
MIXED DB 'iN gOd We TrUsT'    
UPPER DB 15 DUP(?) 
.CODE  
MAIN: MOV AX,@DATA  
MOV DS,AX  
MOV SI,OFFSET MIXED  
MOV BX,OFFSET UPPER  
MOV CX,15  
BACK: MOV AL,[SI]  
CMP AL,61H  
JB OVER  
CMP AL,7AH  
JA OVER  
AND AL,11011111B  
OVER: MOV [BX],AL  
INC SI  
INC BX  
LOOP BACK  
MOV AH,4CH  
INT 21H  
END MAIN